class Config {

    static applicationId = 'com.blankj.aucframe'            // TODO: MODIFY
    static appName = 'AucFrame'                             // TODO: MODIFY

    static compileSdkVersion = 27                           // TODO: MODIFY
    static minSdkVersion = 21                               // TODO: MODIFY
    static targetSdkVersion = 27                            // TODO: MODIFY
    static versionCode = 1_000_000                          // TODO: MODIFY
    static versionName = '1.0.0'// E.g. 1.9.72 => 1,009,072 // TODO: MODIFY

    static gradlePluginVersion = '3.5.0'
    static kotlinVersion = '1.3.50'
    static supportVersion = '27.1.1'

    static depConfig = [
            /*Never delete this line*/
            /*Generated by "config.json"*/
            feature_mock               : new DepConfig(false, true , ":feature:mock"),
            feature_launcher_app       : new DepConfig(true , true , ":feature:launcher:app"),
            feature_feature0_app       : new DepConfig(false, true , ":feature:feature0:app"),
            feature_feature0_pkg       : new DepConfig(true , true , ":feature:feature0:pkg", "com.blankj:feature-feature0-pkg:1.0"),
            feature_feature0_export    : new DepConfig(true , true , ":feature:feature0:export"),
            feature_feature1_app       : new DepConfig(false, true , ":feature:feature1:app"),
            feature_feature1_pkg       : new DepConfig(true , true , ":feature:feature1:pkg"),
            feature_feature1_export    : new DepConfig(true , true , ":feature:feature1:export"),
            lib_base                   : new DepConfig(true , true , ":lib:base"),
            lib_common                 : new DepConfig(true , true , ":lib:common"),
            /*Never delete this line*/
//            feature_template_app       : new DepConfig(":feature:template:app"),
//            feature_template_pkg       : new DepConfig(":feature:template:pkg"),
//            feature_template_export    : new DepConfig(":feature:template:export"),
            plugin_gradle              : new DepConfig(pluginPath: "com.android.tools.build:gradle:$gradlePluginVersion"),
            plugin_kotlin              : new DepConfig(pluginPath: "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"),
            plugin_api                 : new DepConfig(pluginPath: "com.blankj:api-gradle-plugin:1.2", pluginId: "com.blankj.api"),
            plugin_bus                 : new DepConfig(pluginPath: "com.blankj:bus-gradle-plugin:2.4", pluginId: "com.blankj.bus"),

            support_appcompat_v7       : new DepConfig("com.android.support:appcompat-v7:$supportVersion"),
            support_design             : new DepConfig("com.android.support:design:$supportVersion"),
            support_multidex           : new DepConfig("com.android.support:multidex:1.0.2"),
            support_constraint         : new DepConfig("com.android.support.constraint:constraint-layout:1.1.3"),

            kotlin                     : new DepConfig("org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlinVersion"),
            utilcode                   : new DepConfig("com.blankj:utilcode:1.28.0"),
            free_proguard              : new DepConfig("com.blankj:free-proguard:1.0.1"),
            swipe_panel                : new DepConfig("com.blankj:swipe-panel:1.1"),

            leakcanary_android         : new DepConfig("com.squareup.leakcanary:leakcanary-android:2.1"),
    ]
}